# fly.toml file generated for redis-example on 2020-10-30T20:01:11-05:00

app = "redis-example"

[[mounts]]
source = "redis_server"
destination = "/data"

[[services]]
  internal_port = 6379
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = []
    port = "10000"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
