app = "redis-example"

[[mounts]]
  destination = "/data"
  source = "redis_server"

[metrics]
  port = 9091
  path = "/metrics"


# Use the Docker image instead of building from source
#
# [build]
#   image = "flyio/redis:6.2.6"

# Uncomment these lines for public internet access to Redis on port 10000
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [[services.ports]]
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
