app = "redis-example"

[[mounts]]
  destination = "/data"
  source = "redis_server"

# If you want public internet access to Redis on port 10000, uncomment these lines
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [services.concurrency]
#   hard_limit = 25
#   soft_limit = 20
#   [[services.ports]]
#   handlers = []
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
